### ISSUE TITLE
Performance of this code

### ISSUE THREAD

**Issue by zhixuanli** [anirudh-chakravarthy/CASENet#1]
Thank you for your implement so much!

Can you please report some performance about your code on cityscapes dataset?

Thank you again!

Best wishes!

**Comment by anirudh-chakravarthy** [comment]
Hi,

I have been a little busy with something else, so I haven't been able to work on performance evaluation. I found [this resource](https://github.com/zhusiling/SEAL#part-5-evaluation) which can be used for evaluation though.

I'll get to implementing it sometime later though. Hope it helps :)

**Comment by zhixuanli** [comment]
Thanks for your help!!

It's nice to talk to you!
