### ISSUE TITLE
would be useful to use  CASENet for binary edge detection?

### ISSUE THREAD

**Issue by nedaazarmehr** [anirudh-chakravarthy/CASENet#10]
Thank you for sharing your implementation. 
I am wondering would be useful to use the CASENet network for the binary edge detection for the custom dataset or adopting the CASENet network with Hausdorff distance loss (or even cross-entropy loss) instead of multi-label loss? 

Here is an example of[ my ground truth](https://drive.google.com/open?id=1NpK_xow8lSoV_Zkz3YRpkAA7rrIx-0qc):

Thank you in advance

**Comment by anirudh-chakravarthy** [comment]
Hi,

Yes, I don't see why not. I think you could.
