### ISSUE TITLE
Failing at testing

### ISSUE THREAD

**Issue by AlessandroSaviolo** [anirudh-chakravarthy/CASENet#13]
Hi! I'm trying to test your code but something seems to not be working properly. I'm trying to use the command:
```
python get_results_for_benchmark.py -m pretrained_models/model_casenet.pth.tar -f lena.png -d images/ -o output/
```
but got the following error:
```
(truncated)
score_cls_side5.weight is loaded successfully
score_cls_side5.bias is loaded successfully
upsample_cls_side5.weight is loaded successfully
ce_fusion.weight is loaded successfully
ce_fusion.bias is loaded successfully
Traceback (most recent call last):
  File "get_results_for_benchmark.py", line 68, in <module>
    for cls_idx in xrange(num_cls):
NameError: name 'xrange' is not defined
```
I have downloaded the pre-trained model for PyTorch and placed it in the folder _pretrained_models/_. I have downloaded lena.png image from Wikipedia (just for simple test) and placed it in the folder _images/_. What am I missing? Can you help me out?

Thank you!

**Comment by anirudh-chakravarthy** [comment]
Hi,

I think you are using Python3. `xrange` is deprecated in Python3. You can either replace it with `range`, or try to use Python2.

Hope it helps!
