### ISSUE TITLE
Ask for converted numpy pretrained weights

### ISSUE THREAD

**Issue by zhixuanli** [anirudh-chakravarthy/CASENet#2]
Hi, 
After reading this [issue](https://github.com/lijiaman/CASENet/issues/3), I noticed that you are very professional on this problem.

I have tried a lot for converting caffe weights to numpy. But it's very hard to finish this, some bugs always occurs.

So, could you please release the converted pretrained weights or just send to me?

Thank you so much!

My email: zhixuanli@pku.edu.cn

**Comment by anirudh-chakravarthy** [comment]
Hi, 

I have uploaded the pre-trained weights for Pytorch weights at [this drive link](https://drive.google.com/open?id=1zxshISZtq0_S6zFB37F-FhE9wT1ZBrGK). I'll also update the README to provide these weights.

Hope it helps :)

**Comment by zhixuanli** [comment]
Thank you so much!!!
