### ISSUE TITLE
how to get the contour like this?

### ISSUE THREAD

**Issue by sunnyHelen** [anirudh-chakravarthy/CASENet#3]
I run the visualize_multiplelable code. It seems the edge information are output separately to different images. How can I get the contour like this? Thank you.
![image](https://user-images.githubusercontent.com/28101548/62998899-39843d00-beb0-11e9-9e28-6239f358b8b7.png)

**Comment by anirudh-chakravarthy** [comment]
Hi,

I haven't worked on this part yet, but I'm sure it could be done by modifying the visualization script.
