### ISSUE TITLE
Where is the dir 'data_aug'?

### ISSUE THREAD

**Issue by Flames60** [anirudh-chakravarthy/CASENet#4]
I have run the code to preprocess CityScapes data and found that no directory named 'data_aug', with 'list_train_aug.txt' under that.

It is really confusing.

**Comment by anirudh-chakravarthy** [comment]
Hi,

Could you give more details about the problem that you are facing? What is the script you are running?

**Comment by Flames60** [comment]
> Hi,
> 
> Could you give more details about the problem that you are facing? What is the script you are running?

Thanks for your reply.
It is the path you write in the dataloader:

    root_img_folder = "/ais/gobi4/fashion/edge_detection/data_aug" 

    root_label_folder = "/ais/gobi4/fashion/edge_detection/data_aug"

    train_anno_txt = "/ais/gobi4/fashion/edge_detection/data_aug/list_train_aug.txt"

    val_anno_txt = "/ais/gobi4/fashion/edge_detection/data_aug/list_test.txt"

    train_hdf5_file = "/ais/gobi6/jiaman/github/CASENet/utils/train_aug_label_binary_np.h5"

    val_hdf5_file = "/ais/gobi6/jiaman/github/CASENet/utils/test_label_binary_np.h5"

I think maybe 'data_aug' is the same as 'data_proc' in 'cityscapes-preprocess', and I will have a try after finishing the converting the content in 'train.txt' to hdf5, which will take me 2 days.

**Comment by Flames60** [comment]
It runs well, but I need to set the numworkers to 0, since h5py do not support for multiprocess.

Thanks very much.
