### ISSUE TITLE
Pytorch Pretrained Model on Google Drive is broken.

### ISSUE THREAD

**Issue by lzcGitHub** [anirudh-chakravarthy/CASENet#5]
First, thanks a lot for your excellent work, which has made convenient for everyone . Yet I have met a trouble that the Pytorch pretrained model on Google Drive is broken. The extract-caffe-parameters code needs to import caffe, which is so inconvenient in my situation. Could you please upload the Pytorch pretrained model again?

**Comment by anirudh-chakravarthy** [comment]
Hi,

I tried using the link and it was working. For your convenience, I generated another shareable link for the folder: [here.](https://drive.google.com/open?id=1zxshISZtq0_S6zFB37F-FhE9wT1ZBrGK)

Do let me know if it works.

**Comment by lzcGitHub** [comment]
Thanks a lot! It has worked! Very appreciate your kindness and quick reply.
