### ISSUE TITLE
How to preprocess the dataset?

### ISSUE THREAD

**Issue by WhoisZihan** [anirudh-chakravarthy/CASENet#6]
Hi, thanks for sharing your code. I downloaded the gtFine_trainvaltest.zip (241MB) dataset and decompressed it, but I don't quite follow the instructions in the README.

First, `python utils/convert_bin_to_hdf5.py` file contains hardcoded file `val.txt`, but where can I find this file? I don't see such file in the repository or the dataset.

Also, what should I do to run the whole repo from scratch, for example, from dataset preprocess to training, validating and testing? Some more detailed instructions would be a great help.

* Run `python3 utils/convert_bin_to_hdf5.py`
* Run `python3 main.py`

Are the two commands above all that needed to run the repository? 

Thanks!

**Comment by anirudh-chakravarthy** [comment]
Hi,

As discussed [here,](https://github.com/anirudh-chakravarthy/CASENet#input-pre-processing) [cityscapes-preprocess](https://github.com/anirudh-chakravarthy/CASENet/tree/master/cityscapes-preprocess) is used before conversion to hdf5 file format. Preprocessing will generate all the requirements necessary to proceed further. The directory contains its own README for usage, once you preprocess it you can move to the training (or whatever task you wish to perform).

**Comment by WhoisZihan** [comment]
Thanks, I see.
