### ISSUE TITLE
Where can I find the metric F -ODS and AP?

### ISSUE THREAD

**Issue by Keep-Passion** [anirudh-chakravarthy/CASENet#7]
The paper mention that they use the maximum F-measure (MF) at optimal dataset scale (ODS), and average precision (AP) , do you have the code?

**Comment by anirudh-chakravarthy** [comment]
Hi,

I haven't added code for evaluation, just for training and inference.

**Comment by Keep-Passion** [comment]
Hi, thanks for your quick response very much.
