### ISSUE TITLE
How can I obtain .h5 files

### ISSUE THREAD

**Issue by DilaraAlbayrak** [anirudh-chakravarthy/CASENet#9]
Could you provide `train_aug_label_binary_np.h` and `test_label_binary_np.h5` files?

**Comment by anirudh-chakravarthy** [comment]
Hi,

I do not have them locally, as they were extremely large in size. However, follow the instructions in the README and in this [issue](https://github.com/anirudh-chakravarthy/CASENet/issues/6#issue-527183107) and you should be able to generate them yourself. 

Hope this helps

**Comment by JANGSOONMYUN** [comment]
@anirudh-chakravarthy 

Hi, I've finished the pre-processing but there was an error occur after running "python utils/convert_bin_to_hdf5.py"

> Traceback (most recent call last):
>   File "utils/convert_bin_to_hdf5.py", line 66, in <module>
>     convert_num_to_bitfield(label_data, h, w, npz_name, root_folder, h5_file)
>   File "utils/convert_bin_to_hdf5.py", line 30, in convert_num_to_bitfield
>     padded_bit_tensor = torch.cat((torch.zeros(cls_num-actual_len).byte(), bit_tensor.byte()), dim=0)
> RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at ..\aten\src\TH\THGeneral.cpp:188

The main reason of the error is that 'cls_num' is smaller than 'actual_len', so 'cls_num-actual'_len value is under 0.

I don't understand what is 'actual_len'. What does the actual length mean?
